---
os:
  - linux

language: c

node_js:
  - "5.10.1"

env:
  - export NODE_VERSION="5.10.1"

addons:
  apt:
    packages:
      - libgc-dev
      - libgmp-dev

before_install:
  - date
  - cd ${HOME}
  # Setting-up
  - export ATSHOME=${HOME}/ATS1
  - export ATSHOMERELOC=ATS-0.2.12
  - export PATSHOME=${HOME}/ATS2
  - export PATH=${PATH}:${PATSHOME}/bin
  - export TEMPTORY=${TRAVIS_BUILD_DIR}
  - export PATH=${PATH}:${TEMPTORY}/bin
  - export GCC=gcc
  - export CLANG=clang

install:
  - ${TRAVIS_BUILD_DIR}/travis-ci/install-ats1.sh 0.2.12
  - ${TRAVIS_BUILD_DIR}/travis-ci/install-ats2.sh 0.3.12

after_install:
  - date

before_script:
  - date

script:
  # Build ATS1
  - cd ${ATSHOME}
  # ./configure&&make CC=${GCC} all
  - ./configure&&make CC=${GCC} all_ngc
  # Build ATS2
  - cd ${PATSHOME}
  - ./configure&&make CC=${GCC} all
  # Build tempopt
  - cd $TEMPTORY
  - (cd srcgen&&make -f Makefile)
  - (cp -f srcgen/BUILD/tempopt bin/.)
  # Testing CBOOT
  - (cd srcgen && make CBOOT)
  - (cd srcgen/CBOOT && make tempopt && ./tempopt)
  # Build tempacc
  - (cd utils/tempacc&&make copy build)
  - (cp utils/tempacc/BUILD/tempacc bin/.)
  # Build mytempacc
  - (cd utils/mytempacc&&make copy build)
  - (cp utils/mytempacc/BUILD/mytempacc bin/.)
  # Testing of all sorts
  - echo 'running unit-tests...'
  - (cd libats/libc/TEST && make -f Makefile testall)
  - (cd libats/temp/TEST && make -f Makefile testall)
  - (cd libats/temp/bucs320/TEST && make -f Makefile testall)
  - (cd libats/temp/bucs520/TEST && make -f Makefile testall)
  - (cd docgen/CodeBook/RECIPE && make -f Makefile_test testall)
  - (cd contrib/githwxi/TEST00 && make -f Makefile testall)
  - (cd contrib/githwxi/TEST01 && make -f Makefile testall)

after_script:
  - date
